CREATE DATABASE PROJECT;

USE PROJECT;

-- ======================================================================================================================
-- TABLE-1: CONSUMERS
-- ======================================================================================================================

CREATE TABLE consumers (
    Consumer_ID VARCHAR(10) PRIMARY KEY,
    City VARCHAR(255),
    State VARCHAR(255),
    Country VARCHAR(255),
    Latitude DECIMAL(10,7),
    Longitude DECIMAL(10,7),
    Smoker VARCHAR(10),
    Drink_Level VARCHAR(50),
    Transportation_Method VARCHAR(50),
    Marital_Status VARCHAR(20),
    Children VARCHAR(20),
    Age INT,
    Occupation VARCHAR(50),
    Budget VARCHAR(10)
);

-- =======================================================================================================================
-- TABLE-2: CONSUMER_PREFERENCES
-- =======================================================================================================================

CREATE TABLE consumer_preferences (
    Consumer_ID VARCHAR(10),
    Preferred_Cuisine VARCHAR(255),
    FOREIGN KEY (Consumer_ID) REFERENCES consumers(Consumer_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

-- =======================================================================================================================
-- TABLE-3: RESTAURANTS
-- =======================================================================================================================


CREATE TABLE restaurants (
    Restaurant_ID INT PRIMARY KEY,
    Name VARCHAR(255),
    City VARCHAR(255),
    State VARCHAR(255),
    Country VARCHAR(255),
    Zip_Code VARCHAR(10),
    Latitude DECIMAL(11,8),
    Longitude DECIMAL(11,8),
    Alcohol_Service VARCHAR(50),
    Smoking_Allowed VARCHAR(50),
    Price VARCHAR(10),
    Franchise VARCHAR(5),
    Area VARCHAR(50),
    Parking VARCHAR(50)
);

-- =======================================================================================================================
-- TABLE-4:RESTAURANT_CUISINES
-- =======================================================================================================================

CREATE TABLE restaurant_cuisines (
    Restaurant_ID INT,
    Cuisine VARCHAR(255),
    FOREIGN KEY (Restaurant_ID) REFERENCES restaurants(Restaurant_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

-- =======================================================================================================================
-- TABLE-5: RATINGS
-- =======================================================================================================================

CREATE TABLE ratings (
    Consumer_ID VARCHAR(10),
    Restaurant_ID INT,
    Overall_Rating INT,
    Food_Rating INT,
    Service_Rating INT,
    FOREIGN KEY (Consumer_ID) REFERENCES consumers(Consumer_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
        
    FOREIGN KEY (Restaurant_ID) REFERENCES restaurants(Restaurant_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);



SELECT * FROM CONSUMERS;

SELECT * FROM CONSUMER_PREFERENCES;

SELECT * FROM RATINGS;

SELECT * FROM RESTAURANT_CUISINES;

SELECT * FROM RESTAURANTS;

-- ✅ WHERE CLAUSE QUESTIONS

-- 1. LIST CONSUMERS IN CITY 'CUERNAVACA'.

SELECT * FROM CONSUMERS WHERE CITY = 'Cuernavaca';

-- 2. FIND CONSUMER_ID,AGE,OCCUPTION OF CONSUMERS WHO ARE STUDENTS AND SMOKERS.

SELECT CONSUMER_ID,AGE,OCCUPATION FROM CONSUMERS;

-- 3.LIST RESTAURANTS SERVING 'WINE & BEER' WITH 'MEDIUM' PRICE.

SELECT * FROM RESTAURANTS WHERE ALCOHOL_SERVICE = 'Wine & Beer' AND PRICE = 'Medium';

-- 4. NAME AND CITIES OF RESTAURANT FRANCHISES.

SELECT NAME,CITY FROM RESTAURANTS WHERE FRANCHISE = 'Yes';

-- 5. LIST ALL RATINGS WHERE OVERALL_RATING = 'HIGHLY'.

SELECT * FROM RATINGS WHERE OVERALL_RATING = 2;

-- ✅ JOIN + SUBQUERY QUERIES

-- 1. RESTAURANTS THAT HAVE AN OVERALL_RATING = 2

SELECT DISTINCT R.RESTAURANT_ID, R.NAME, R.CITY
FROM RESTAURANTS R
JOIN RATINGS RT
    ON R.RESTAURANT_ID = RT.RESTAURANT_ID
WHERE RT.OVERALL_RATING = 2;

-- 2. CONSUMERS WHO RATED RESTAURANTS IN 'CUERNAVACA'.

SELECT DISTINCT C.CONSUMER_ID, C.CITY
FROM CONSUMERS C
JOIN RATINGS RT
    ON C.CONSUMER_ID = RT.CONSUMER_ID
JOIN RESTAURANTS R
    ON RT.RESTAURANT_ID = R.RESTAURANT_ID
WHERE R.CITY = 'Cuernavaca';

-- 3. RESTAURANTS SERVING 'MEXICAN' AND RATED BY 'U1001'

SELECT DISTINCT R.RESTAURANT_ID, R.NAME
FROM RESTAURANTS R
JOIN RESTAURANT_CUISINES RC
    ON R.RESTAURANT_ID = RC.RESTAURANT_ID
JOIN RATINGS RT
    ON R.RESTAURANT_ID = RT.RESTAURANT_ID
WHERE RC.CUISINE = 'Mexican'
  AND RT.CONSUMER_ID = 'U1001';
  
  -- 4. CONSUMERS PREFERRING 'AMERICIAN' CISINE AND HAVING 'MEDIUM' BUDGET
  
  SELECT DISTINCT C.CONSUMER_ID, C.AGE, C.BUDGET
FROM CONSUMERS C
JOIN CONSUMER_PREFERENCES CP
    ON C.CONSUMER_ID = CP.CONSUMER_ID
WHERE CP.PREFERRED_CUISINE = 'American'
  AND C.BUDGET = 'Medium';

-- 5.RESTAURANTS WHERE FOOD_RATING IS LOWER THAN AVERAGE FOOD_RATING

SELECT R.RESTAURANT_ID, R.NAME
FROM RESTAURANTS R
JOIN RATINGS RT
    ON R.RESTAURANT_ID = RT.RESTAURANT_ID
WHERE RT.FOOD_RATING < (
    SELECT AVG(FOOD_RATING)
    FROM RATINGS
);

-- 6. CONSUMERS WHO RATED RESTAURANTS BUT NOT LTALIAN RESTAURANTS

SELECT DISTINCT C.CONSUMER_ID
FROM CONSUMERS C
JOIN RATINGS RT
    ON C.CONSUMER_ID = RT.CONSUMER_ID
WHERE C.CONSUMER_ID NOT IN (
    SELECT RT2.CONSUMER_ID
    FROM RATINGS RT2
    JOIN RESTAURANT_CUISINES RC2
        ON RT2.RESTAURANT_ID = RC2.RESTAURANT_ID
    WHERE RC2.CUISINE = 'Italian'
);

-- 7. RESTAURANTS RATED BY CONSUMERS OLDER THAN 30.

SELECT DISTINCT R.RESTAURANT_ID, R.NAME
FROM RESTAURANTS R
JOIN RATINGS RT
    ON R.RESTAURANT_ID = RT.RESTAURANT_ID
JOIN CONSUMERS C
    ON RT.CONSUMER_ID = C.CONSUMER_ID
WHERE C.AGE > 30;

-- 8.CONSUMERS WHO PREFER 'MEXICAN' AND GAVE RATING 0

SELECT DISTINCT C.CONSUMER_ID
FROM CONSUMERS C
JOIN CONSUMER_PREFERENCES CP
    ON C.CONSUMER_ID = CP.CONSUMER_ID
JOIN RATINGS RT
    ON C.CONSUMER_ID = RT.CONSUMER_ID
WHERE CP.PREFERRED_CUISINE = 'Mexican'
  AND RT.OVERALL_RATING = 0;

-- 9.'PIZZERIA' RESTAURANTS IN CITIES WHERE 'STUDENNT' CONSUMERS LIVE

SELECT DISTINCT R.RESTAURANT_ID, R.NAME, R.CITY
FROM RESTAURANTS R
JOIN RESTAURANT_CUISINES RC
    ON R.RESTAURANT_ID = RC.RESTAURANT_ID
WHERE RC.CUISINE = 'Pizzeria'
  AND R.CITY IN (
      SELECT CITY
      FROM CONSUMERS
      WHERE OCCUPATION = 'Student'
  );

-- 10. SOCIAL DRINKERS WHO RATED RESTAURANTS WITH 'NO' PARKING

SELECT DISTINCT C.CONSUMER_ID, C.AGE, R.NAME
FROM CONSUMERS C
JOIN RATINGS RT
    ON C.CONSUMER_ID = RT.CONSUMER_ID
JOIN RESTAURANTS R
    ON RT.RESTAURANT_ID = R.RESTAURANT_ID
WHERE C.DRINK_LEVEL = 'Social'
  AND R.PARKING = 'No';
  
-- ADVANCED SQL

-- 1. USE A CTE TO FIND CONSUMERS IN 'San Luis Potosi' AND LIST THEIR Mexican RESTAURANT RATINGS WITH
-- OVERALL_RATING = 2


WITH CTE_CONSUMERS AS (
    SELECT CONSUMER_ID
    FROM CONSUMERS
    WHERE CITY = 'San Luis Potosi'
)

SELECT RT.CONSUMER_ID, RT.RESTAURANT_ID, RT.OVERALL_RATING
FROM RATINGS RT
JOIN RESTAURANT_CUISINES RC
    ON RT.RESTAURANT_ID = RC.RESTAURANT_ID
WHERE RC.CUISINE = 'Mexican'
  AND RT.OVERALL_RATING = 2
  AND RT.CONSUMER_ID IN (SELECT CONSUMER_ID FROM CTE_CONSUMERS);

-- 2. FOR EACH OCCUPATION,FIND THE AVERAGE AGE OF CONSUMERS WHO HAVE RATED AT LEAST ONE RESTAURANT

WITH CTE_RATERS AS (
    SELECT DISTINCT CONSUMER_ID
    FROM RATINGS
)

SELECT C.OCCUPATION, AVG(C.AGE) AS AVG_AGE
FROM CONSUMERS C
WHERE C.CONSUMER_ID IN (SELECT CONSUMER_ID FROM CTE_RATERS)
GROUP BY C.OCCUPATION;


-- 3.RANKS RATING INSIDE EACH RESTAURANT (ONLY FOR RESTAURANTS IN 'Cuernavaca')

WITH CTE_R AS (
    SELECT RT.RESTAURANT_ID, RT.CONSUMER_ID, RT.OVERALL_RATING
    FROM RATINGS RT
    JOIN RESTAURANTS R
        ON RT.RESTAURANT_ID = R.RESTAURANT_ID
    WHERE R.CITY = 'Cuernavaca'
)

SELECT RESTAURANT_ID, CONSUMER_ID, OVERALL_RATING,
       RANK() OVER (PARTITION BY RESTAURANT_ID ORDER BY OVERALL_RATING DESC) AS RANKING
FROM CTE_R;


-- 4. FOR EACH RATING, ALSO SHOW THE AVERAGE RATING THAT CONSUMER GIVES (WINDOW FUNCTION)

SELECT RT.CONSUMER_ID, RT.RESTAURANT_ID, RT.OVERALL_RATING,
       AVG(RT.OVERALL_RATING) OVER (PARTITION BY RT.CONSUMER_ID) AS AVG_CONSUMER_RATING
FROM RATINGS RT;

-- 5.FOR STUDENTS WITH 'LOW' BUDGET, SHOW THEIR TOP 3 PREFERRED CUISINES USING ROW_NUMBER

WITH CTE_CP AS (
    SELECT C.CONSUMER_ID, CP.PREFERRED_CUISINE,
           ROW_NUMBER() OVER (PARTITION BY C.CONSUMER_ID ORDER BY CP.PREFERRED_CUISINE) AS RN
    FROM CONSUMERS C
    JOIN CONSUMER_PREFERENCES CP
        ON C.CONSUMER_ID = CP.CONSUMER_ID
    WHERE C.OCCUPATION = 'Student'
      AND C.BUDGET = 'Low'
)

SELECT CONSUMER_ID, PREFERRED_CUISINE
FROM CTE_CP
WHERE RN <= 3;

-- 6.CREATE A VIEW OF MEXICAN RESTAURANTS WITH AVG OVERALL_RATING > 1.5

CREATE VIEW HIGHLY_RATED_MEXICAN_RESTAURANTS AS
SELECT R.RESTAURANT_ID, R.NAME,
       AVG(RT.OVERALL_RATING) AS AVG_RATING
FROM RESTAURANTS R
JOIN RESTAURANT_CUISINES RC
    ON R.RESTAURANT_ID = RC.RESTAURANT_ID
JOIN RATINGS RT
    ON R.RESTAURANT_ID = RT.RESTAURANT_ID
WHERE RC.CUISINE = 'Mexican'
GROUP BY R.RESTAURANT_ID, R.NAME
HAVING AVG_RATING > 1.5;

SELECT * FROM HIGHLY_RATED_MEXICAN_RESTAURANTS;

-- 7. STORED PROCEDURE:GET ALL RATIINGS FOR A RESTAURANT ABOVE A GIVEN THRESHOLD

DELIMITER $$

CREATE PROCEDURE GET_RESTAURANT_RATINGS_ABOVE_THRESHOLD (
    IN P_RESTAURANT_ID INT,
    IN P_MIN_RATING INT
)
BEGIN
    SELECT *
    FROM RATINGS
    WHERE RESTAURANT_ID = P_RESTAURANT_ID
      AND OVERALL_RATING >= P_MIN_RATING;
END $$

DELIMITER ;

CALL GET_RESTAURANT_RATINGS_ABOVE_THRESHOLD(132564, 1);

-- 8.TOP 2 HIGHEST-RATED RESTURANTS PER CUISINE

WITH CTE_RANKED AS (
    SELECT RC.CUISINE,
           R.RESTAURANT_ID,
           R.NAME,
           AVG(RT.OVERALL_RATING) AS AVG_RATING,
           RANK() OVER (
                PARTITION BY RC.CUISINE
                ORDER BY AVG(RT.OVERALL_RATING) DESC
           ) AS RN
    FROM RESTAURANT_CUISINES RC
    JOIN RESTAURANTS R
        ON RC.RESTAURANT_ID = R.RESTAURANT_ID
    JOIN RATINGS RT
        ON R.RESTAURANT_ID = RT.RESTAURANT_ID
    GROUP BY RC.CUISINE, R.RESTAURANT_ID, R.NAME
)

SELECT *
FROM CTE_RANKED
WHERE RN <= 2;

-- 9.CREATE A VIEW OF CUSTOMER AVERAGE RATINGS

CREATE VIEW CONSUMER_AVERAGE_RATINGS AS
SELECT CONSUMER_ID,
       AVG(OVERALL_RATING) AS AVG_RATING
FROM RATINGS
GROUP BY CONSUMER_ID;

SELECT * FROM CONSUMER_AVERAGE_RATINGS;

-- 10.USING THE ABOVE VIEW,FIND THE TOP 5 CONSUMERS BY AVERAGE RATING AND SHOW HOW MANY MEXICAN RESTAURANTS THEY RATED

SELECT CAR.CONSUMER_ID,
       CAR.AVG_RATING,
       COUNT(RC.RESTAURANT_ID) AS MEXICAN_RESTAURANTS_RATED
FROM CONSUMER_AVERAGE_RATINGS CAR
LEFT JOIN RATINGS RT
    ON CAR.CONSUMER_ID = RT.CONSUMER_ID
LEFT JOIN RESTAURANT_CUISINES RC
    ON RT.RESTAURANT_ID = RC.RESTAURANT_ID
    AND RC.CUISINE = 'Mexican'
GROUP BY CAR.CONSUMER_ID, CAR.AVG_RATING
ORDER BY CAR.AVG_RATING DESC
LIMIT 5;

-- 11.STORED PROCEDURE: CONSUMER SEGMENT + RESTAURANT PERFORMANCE

DELIMITER $$

CREATE PROCEDURE GET_CONSUMER_SEGMENT_AND_RESTAURANT_PERFORMANCE (
    IN P_CONSUMER_ID VARCHAR(10)
)
BEGIN

    -- STEP 1: GET CONSUMER SEGMENT
    SELECT BUDGET,
           CASE
               WHEN BUDGET = 'Low' THEN 'Budget Conscious'
               WHEN BUDGET = 'Medium' THEN 'Moderate'
               WHEN BUDGET = 'High' THEN 'Premium'
               ELSE 'Unknown'
           END AS SPENDING_SEGMENT
    FROM CONSUMERS
    WHERE CONSUMER_ID = P_CONSUMER_ID;

    -- STEP 2: RESTAURANT PERFORMANCE
    SELECT R.NAME AS RESTAURANT_NAME,
           RT.OVERALL_RATING AS CONSUMER_RATING,
           
           (SELECT AVG(OVERALL_RATING)
            FROM RATINGS
            WHERE RESTAURANT_ID = RT.RESTAURANT_ID) AS AVG_RESTAURANT_RATING,
           
           CASE
               WHEN RT.OVERALL_RATING > 
                    (SELECT AVG(OVERALL_RATING)
                     FROM RATINGS
                     WHERE RESTAURANT_ID = RT.RESTAURANT_ID)
                    THEN 'Above Average'
               WHEN RT.OVERALL_RATING = 
                    (SELECT AVG(OVERALL_RATING)
                     FROM RATINGS
                     WHERE RESTAURANT_ID = RT.RESTAURANT_ID)
                    THEN 'At Average'
               ELSE 'Below Average'
           END AS PERFORMANCE_FLAG,
           
           RANK() OVER (ORDER BY RT.OVERALL_RATING DESC) AS RANKING
           
    FROM RATINGS RT
    JOIN RESTAURANTS R
        ON RT.RESTAURANT_ID = R.RESTAURANT_ID
    WHERE RT.CONSUMER_ID = P_CONSUMER_ID;

END $$

DELIMITER ;


CALL GET_CONSUMER_SEGMENT_AND_RESTAURANT_PERFORMANCE('U1001');